name: freedom_timer
description: "A new Flutter project."
publish_to: "JunYoung"
version: 0.3.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.3
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  webview_flutter: ^4.4.2
  flutter_lints: ^5.0.0
  kakao_flutter_sdk: ^1.9.7+3
  fluttertoast: ^9.0.0
  provider: ^6.1.5+1
  # 캘린더
  table_calendar: ^3.0.9
  # 차트
  fl_chart: ^0.65.0
  # 한국어 지원 (선택)
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/animations/ # Lottie 애니메이션 전체 등록
    - assets/images/
    - assets/icon/
  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
